### PR TITLE
Multiple tabs all commits

### PR DESCRIPTION
**Pull request by Snehal1894**
1. The entry forms were changes
2. Removed 'session' entries
3. Edit and delete views changed

### CODE REVIEW

**Comment by sergpolly** [comment]
amazing stuff @Snehal1894  ! clear and simple ! `on_delete.CASCADE` -> `on_delete.SET_NULL`

**Comment by sergpolly** [comment]
so, should we merge the whole thing now ?

**Comment by Snehal1894** [comment]
> so, should we merge the whole thing now ?

Yes, we can.

**Comment by sergpolly** [comment]
done! but now we'd need to update the version that's running on `clims.dekkerlab.org` - and before hand notify everyone via email - that's how @nandankita used to do it

**Comment by sergpolly** [comment]
oh , that was merge to a branch - hold on - we have to  create a PR to the `master` ...

**Pull request merged**
